releases:
  - name: rediscart
    chart: charts/redis
    values: 
      - redis-cart.yaml
      - appReplicas: "1"
      - volumeName: "redis-cart-data"
  
  - name: emailservice
    chart: charts/microservice
    values:
      - email-service.yaml

  - name: cartservice
    chart: charts/microservice
    values:
      - cartservice.yaml    

  - name: currencyservice
    chart: charts/microservice
    values:
      - currencyservice.yaml   

  - name: paymentservice
    chart: charts/microservice
    values:
      - paymentservice.yaml

  - name: recommendationservice
    chart: charts/microservice
    values:
      - recommendationservice.yaml

  - name: productcatalogservice
    chart: charts/microservice
    values:
      - productcatalogservice.yaml

  - name: shippingservice
    chart: charts/microservice
    values:
      - shippingservice.yaml

  - name: adservice
    chart: charts/microservice
    values:
      - adservice.yaml

  - name: checkoutservice
    chart: charts/microservice
    values:
      - checkout.yaml

  - name: frontendservice
    chart: charts/microservice
    values:
      - frontend.yaml
